### ISSUE TITLE
Suggestion: split and “modularize”

### ISSUE THREAD

**Issue by amiryal** [MeirKriheli/dotvim#1]
Hi,

**Definitions**: _I_, _me_, _my_ – anyone cloning and using your `dotvim`.

Would it be possible, and would you consider, to invert the relationship between `.vim/vimrc.local` and `.vimrc`?  It would be nice to have my own `.vimrc` managed in a `vcsh` repo, and be able to clone your repo, either with `mr` or as another `vcsh` superposition in `.vim/MeirKriheli`, from whence I’ll be able to `source` individual files, e.g. `keyboard_shortcuts.vimrc`, `ctrlp_settings.vimrc`, etc.

You can keep your main `vimrc` file in the repo as well for my reference, with all the Vundle+plugins stuff and sourcing all your other files, but I will be able to choose whether or not to symlink it as-is.

What do you think?

**Comment by MeirKriheli** [comment]
@amiryal I don't mind doing that, just need to find the time. Would be great If you'll can send a PR.

**Comment by MeirKriheli** [comment]
@amiryal Hope that's what you had in mind, if not please let me know.

**Comment by amiryal** [comment]
It will serve the purpose perfectly. Thanks!
